CREATE TABLE `USUARIO` (
  `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `ACTIVO` char(1) NOT NULL,
  `ROL` int NOT NULL,
  PRIMARY KEY (`ID_USUARIO`)
  );

CREATE TABLE `ROL`(
`ID_ROLusuariousuario` INT NOT NULL,
`NOMBRE` VARCHAR(50),
CONSTRAINT `id_usuario` PRIMARY KEY (`ID_USUARIO` ASC)
);

INSERT INTO USUARIO (nombre) VALUES ('Jorge');
INSERT INTO USUARIO (nombre) VALUES ('Pedro');
INSERT INTO USUARIO (nombre) VALUES ('Miguel');


INSERT INTO `ROL` VALUES (1,'ADMINISTRADOR');
INSERT INTO `ROL` VALUES (2,'AUDITOR');
INSERT INTO `ROL` VALUES (3,'AUXILIAR'); 
COMMIT;
